### ISSUE TITLE
model import error 

### ISSUE THREAD

**Issue by haven-jeon** [SKT-AI/KoGPT2#5]
다른 디렉토리에서 예제 코드를 실행시 아래와 같은 에러 발생

```python
from kogpt2.pytorch_kogpt2 import get_pytorch_kogpt2_model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gogamza/miniconda3/lib/python3.7/site-packages/kogpt2/pytorch_kogpt2.py", line 23, in <module>
    from model.torch_gpt2 import GPT2Config, GPT2LMHeadModel
ModuleNotFoundError: No module named 'model'
```

**Comment by haven-jeon** [comment]
f2ffadd89
